version: '3'

services:
  jupyterlab:
    build: .
    volumes:
      - .:/code
    ports:
      - "127.0.0.1:8889:8889"
    command: jupyter-lab --port=8889 --ip=0.0.0.0 --allow-root --NotebookApp.token=''